version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - docker.env

  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
